CREATE TABLE IF NOT EXISTS "Server" (
	"id" VARCHAR NOT NULL,
	"Name" VARCHAR DEFAULT null,
	"Referant" VARCHAR DEFAULT null,
	"hostname" VARCHAR DEFAULT null,
	"IP_Address_id" VARCHAR NOT NULL,
	"BMC_IP_address_id" VARCHAR DEFAULT null,
	"NAT_IP_address_id" VARCHAR,
	"Exception_EDR" VARCHAR,
	"Exception_SIEM" VARCHAR,
	"fqdn" VARCHAR,
	"domain" VARCHAR,
	"Owner_id" VARCHAR,
	"Support_id" VARCHAR,
	"Localisation_id" VARCHAR,
	"OS_id" VARCHAR,
	"Type" VARCHAR,
	"EDR_id" VARCHAR,
	"Monitor_id" VARCHAR,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id") REFERENCES "VLAN"("router")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("BMC_IP_address_id") REFERENCES "IP address"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("OS_id") REFERENCES "OS"("id")
	ON UPDATE NO ACTION ON DELETE SET NULL,
	FOREIGN KEY ("IP_Address_id") REFERENCES "IP address"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("Referant") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("Owner_id") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("Support_id") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("Localisation_id") REFERENCES "Localisation"("id")
	ON UPDATE NO ACTION ON DELETE SET NULL,
	FOREIGN KEY ("NAT_IP_address_id") REFERENCES "IP address"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Localisation" (
	"id" VARCHAR NOT NULL,
	"Country" VARCHAR,
	"City" VARCHAR,
	"Room" VARCHAR,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Application" (
	"id" INTEGER NOT NULL,
	"Owner" VARCHAR DEFAULT null,
	"support" VARCHAR DEFAULT null,
	"Name" VARCHAR NOT NULL,
	"Description" TEXT,
	"Criticality" VARCHAR,
	"Hosted" VARCHAR,
	PRIMARY KEY("id"),
	FOREIGN KEY ("Owner") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("support") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("Hosted") REFERENCES "Server"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "User" (
	"id" VARCHAR NOT NULL,
	"Name" VARCHAR DEFAULT null,
	"email" VARCHAR DEFAULT null,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "IP address" (
	"id" VARCHAR NOT NULL,
	"IPv4" VARCHAR NOT NULL,
	-- VLAN contains VLAN id
	"VLAN_id" VARCHAR DEFAULT null,
	"IP public" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "VLAN" (
	"router" VARCHAR,
	"Gateway" VARCHAR,
	"id" VARCHAR NOT NULL,
	"Name" VARCHAR,
	"CIDR" VARCHAR NOT NULL,
	"Advertised" BOOLEAN,
	PRIMARY KEY("id"),
	FOREIGN KEY ("Gateway") REFERENCES "IP address"("id")
	ON UPDATE NO ACTION ON DELETE SET NULL,
	FOREIGN KEY ("id") REFERENCES "IP address"("VLAN_id")
	ON UPDATE NO ACTION ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "OS" (
	"id" VARCHAR NOT NULL,
	"Name" VARCHAR,
	"Version" VARCHAR,
	"EDR" BOOLEAN,
	"type" VARCHAR,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Team" (
	"id" VARCHAR NOT NULL,
	"user" VARCHAR,
	PRIMARY KEY("id"),
	FOREIGN KEY ("user") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE SET NULL
);
